databases:
  - name: study-pet-db
    databaseName: study_pet_production
    user: study_pet
    plan: free
    region: oregon

services:
  - type: web
    name: study-pet
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: study-pet-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
      - key: POSTGRES_HOST
        fromDatabase:
          name: study-pet-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: study-pet-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: study-pet-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: study-pet-db
          property: password

  - type: web
    name: study-pet-frontend
    plan: free
    staticPublishPath: ./study_pet_frontend
    buildCommand: echo "No build needed for static site"
