# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>

development:
  <<: *default
  database: study_pet_development

test:
  <<: *default
  database: study_pet_test

production:
  primary: &primary_production
    <<: *default
    database: study_pet_production
  cache:
    <<: *primary_production
    database: study_pet_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: study_pet_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: study_pet_production_cable
    migrations_paths: db/cable_migrate
